### PR TITLE
1.19.3 update

### PR DESCRIPTION
**Pull request by Julienraptor01**
ehe
didn't require much except a mixin fix

### CODE REVIEW

**Comment by Julienraptor01** [comment]
for people who are waiting for the PR to be accepted and don't want to compile the mod, here is it.
(i have to put it in a zip for GH to accept it, so download and the jar is right in, you just need to extract it)
[bears-armor-hud-0.3.8.zip](https://github.com/BerdinskiyBear/armor-hud/files/10805428/bears-armor-hud-0.3.8.zip)

**Comment by BerdinskiyBear** [comment]
Thank you, but it is not necessary anymore since I updated mod for 1.19.4

**Comment by Julienraptor01** [comment]
> Thank you, but it is not necessary anymore since I updated mod for 1.19.4

Fine

**Comment by Xzhong2023** [comment]
I want to have 1.19.3

**Comment by Julienraptor01** [comment]
> I want to have 1.19.3
>  

You can use the jar in the zip above

**Pull request closed without merging**
