### PR TITLE
1.19.2 Update

### PR DESCRIPTION
**Pull request by Julienraptor01**

### CODE REVIEW

**Comment by Julienraptor01** [comment]
actually it's my 1.19.2 update

**Comment by BerdinskiyBear** [comment]
I will review changed today or tomorrow. It seems that you have done everything. If nothing needs to be changed, I will merge and publish updated jars

**Comment by Julienraptor01** [comment]
> I will review changed today or tomorrow. It seems that you have done everything. If nothing needs to be changed, I will merge and publish updated jars

Actually i think i forgot to update recommended in fabric.mod.json but it'll be a quick fix

**Comment by Julienraptor01** [comment]
The recommended were effectively vastly outaded and i did forgot to update them but it's fixed

**Pull request merged**
